name: Feature request
description: File a feature request
title: "[Feature]: "
labels: ["enhancement"]
assignees:
  - lennis-dev
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a feature request
  - type: textarea
    id: related-to-problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when [...]
      value: "I'm always frustrated when [...]"
    validations:
      required: false
  - type: textarea
    id: describe-the-solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: A clear and concise description of what you want to happen.
      value: "The solution is..."
    validations:
      required: true
  - type: textarea
    id: alternatives-considered
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
      value: "I think about..."
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder: "Text, screenshots, ..."
      value: "Text, screenshots, ..."
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/synxit/synxit-server/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
